# Generated by Django 3.1.7 on 2021-03-16 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_name', models.CharField(max_length=264, unique=True)),
                ('panel_width', models.IntegerField()),
                ('panel_height', models.IntegerField()),
                ('panel_pixel_width', models.IntegerField()),
                ('panel_pixel_height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=264, unique=True)),
                ('panels_wide', models.IntegerField()),
                ('panels_high', models.IntegerField()),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_app.ledpanel')),
            ],
        ),
    ]
