# Generated by Django 3.1.7 on 2021-03-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='refresh_rate',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
