# Generated by Django 3.1.7 on 2021-03-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0002_screen_refresh_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledpanel',
            name='panel_curent_draw',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
